# Generated by Django 5.0.6 on 2024-05-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='category_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Armchair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kreslo Nomi')),
                ('chairtype', models.CharField(max_length=150, verbose_name='Stul Turi')),
                ('upholsterymaterial', models.CharField(max_length=150, verbose_name='Material')),
                ('upholsterycolor', models.CharField(max_length=100, verbose_name='Rang')),
                ('reclining', models.CharField(max_length=100, verbose_name='Yotgan holda')),
                ('permissibleload', models.IntegerField(verbose_name='Ruxsat etilgan yuk')),
                ('photo', models.ImageField(upload_to='armchair_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='GamingBuilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='PC Nomi')),
                ('cpu', models.CharField(max_length=200, verbose_name='Protsessor')),
                ('cooler', models.CharField(max_length=100, verbose_name='Sovutgich')),
                ('ram', models.IntegerField()),
                ('ssd', models.IntegerField(verbose_name='Qattiq holat diski')),
                ('hdd', models.IntegerField(verbose_name='qattiq disk')),
                ('gpu', models.CharField(max_length=150, verbose_name='Video Karta')),
                ('psu', models.CharField(max_length=100, verbose_name='Quvvatlantirish Manbai')),
                ('case', models.CharField(max_length=100, verbose_name='Keys')),
                ('photo', models.ImageField(upload_to='pc_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Klaviatura Nomi')),
                ('keyboardtype', models.CharField(max_length=50, verbose_name='Klaviatura turi')),
                ('switchtype', models.CharField(max_length=50, verbose_name='Kalit turi')),
                ('interface', models.CharField(max_length=30, verbose_name='Interfeys')),
                ('backlight', models.CharField(max_length=30, verbose_name="Orqa yorug'lik")),
                ('numberofkeys', models.IntegerField(verbose_name='Tugmalar soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Naxr')),
                ('photo', models.ImageField(upload_to='keyboard_photos/', verbose_name='Rasm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='LapTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Noutbuk Nomi')),
                ('cpu', models.CharField(max_length=150, verbose_name='Protsessor')),
                ('ram', models.IntegerField()),
                ('ssd', models.IntegerField()),
                ('gpu', models.CharField(max_length=150, verbose_name='Video Karta')),
                ('display', models.CharField(max_length=255, verbose_name='Ekran')),
                ('photo', models.ImageField(upload_to='laptop_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Mice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sichqoncha Nomi')),
                ('sensortype', models.CharField(max_length=150, verbose_name='Sensor turi')),
                ('maximumdpicpiresolution', models.IntegerField(verbose_name='Maksimal DPI/CPI ruxsati')),
                ('numberofbuttons', models.IntegerField(verbose_name='Tugmalar soni')),
                ('pullingrate', models.CharField(max_length=100, verbose_name='Saylov darajasi')),
                ('operatingmode', models.CharField(max_length=50, verbose_name='Ishlash rejimi')),
                ('photo', models.ImageField(upload_to='mice_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Monitor Nomi')),
                ('diagonal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ekran Diagonali')),
                ('screentype', models.CharField(max_length=30, verbose_name='Ekran turi')),
                ('matrixtype', models.CharField(max_length=50, verbose_name='Matritsa Turi')),
                ('permission', models.CharField(max_length=100, verbose_name='Ruxsat')),
                ('framerate', models.CharField(max_length=50, verbose_name='Kadr tezligi')),
                ('interface', models.CharField(max_length=100, verbose_name='Interfeys')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('photo', models.ImageField(upload_to='monitor_photos/', verbose_name='Rasm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
